name: Node.js test build job

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Node.js version'
        required: true
        default: 'v24.4.1'

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.inputs.version }}
    strategy:
      matrix:
        name: ['node']
        binaries: ['gnu', 'musl']

    steps:
      - name: Check version
        run: |
          echo "Node.js current version: ${version}"

          major_version=$(echo $version | sed 's/^v//' | cut -d '.' -f 1)
          echo "major_version=${major_version}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: loong64/node-unofficial-builds
          path: unofficial-builds

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/workdir/.ccache
          key: ${{ matrix.name }}-${{ matrix.binaries }}-v${{ env.major_version }}-

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Set workdir
        run: |
          mkdir -p ${{ github.workspace }}/workdir/staging
          sudo chmod -R 777 ${{ github.workspace }}/workdir/staging
          sudo chown -R 1000:docker ${{ github.workspace }}/workdir/staging

      - name: Build node.js
        run: |
          if [ "${{ env.major_version }}" = "24" ]; then
            sed -i 's@stable@mainline@g' recipes/loong64-${{ matrix.binaries }}/Dockerfile
          fi

          ./bin/local_build.sh -r loong64-${{ matrix.binaries }} -v ${{ env.version }} -w ${{ github.workspace }}/workdir
          cd ${{ github.workspace }}/workdir/staging/release/${{ env.version }}

          case ${{ matrix.binaries }} in
            gnu)
              sha256sum node-${{ env.version }}-linux-loong64.tar.gz > node-${{ env.version }}-linux-loong64.tar.gz.sha256
              sha256sum node-${{ env.version }}-linux-loong64.tar.xz > node-${{ env.version }}-linux-loong64.tar.xz.sha256
              ;;
            musl)
              sha256sum node-${{ env.version }}-linux-loong64-musl.tar.gz > node-${{ env.version }}-linux-loong64-musl.tar.gz.sha256
              sha256sum node-${{ env.version }}-linux-loong64-musl.tar.xz > node-${{ env.version }}-linux-loong64-musl.tar.xz.sha256
              ;;
          esac
        working-directory: unofficial-builds

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-${{ env.version }}-${{ matrix.binaries }}
          path: ${{ github.workspace }}/workdir/staging/release/${{ env.version }}/*